/* SPDX-License-Identifier: LGPL-2.1-or-later */

/* ga-error.h - Header for error types (systemd-resolved compatibility) */

#ifndef __GA_ERROR_H__
#define __GA_ERROR_H__

#include <glib-object.h>

G_BEGIN_DECLS

GQuark ga_error_quark(void);

#define GA_ERROR ga_error_quark()

/* Error codes matching Avahi error codes */
typedef enum {
    GA_ERROR_OK = 0,
    GA_ERROR_FAILURE = -1,
    GA_ERROR_BAD_STATE = -2,
    GA_ERROR_INVALID_HOST_NAME = -3,
    GA_ERROR_INVALID_DOMAIN_NAME = -4,
    GA_ERROR_NO_NETWORK = -5,
    GA_ERROR_INVALID_TTL = -6,
    GA_ERROR_IS_PATTERN = -7,
    GA_ERROR_COLLISION = -8,
    GA_ERROR_INVALID_RECORD = -9,
    GA_ERROR_INVALID_SERVICE_NAME = -10,
    GA_ERROR_INVALID_SERVICE_TYPE = -11,
    GA_ERROR_INVALID_PORT = -12,
    GA_ERROR_INVALID_KEY = -13,
    GA_ERROR_INVALID_ADDRESS = -14,
    GA_ERROR_TIMEOUT = -15,
    GA_ERROR_TOO_MANY_CLIENTS = -16,
    GA_ERROR_TOO_MANY_OBJECTS = -17,
    GA_ERROR_TOO_MANY_ENTRIES = -18,
    GA_ERROR_OS = -19,
    GA_ERROR_ACCESS_DENIED = -20,
    GA_ERROR_INVALID_OPERATION = -21,
    GA_ERROR_DBUS_ERROR = -22,
    GA_ERROR_DISCONNECTED = -23,
    GA_ERROR_NO_MEMORY = -24,
    GA_ERROR_INVALID_OBJECT = -25,
    GA_ERROR_NO_DAEMON = -26,
    GA_ERROR_INVALID_INTERFACE = -27,
    GA_ERROR_INVALID_PROTOCOL = -28,
    GA_ERROR_INVALID_FLAGS = -29,
    GA_ERROR_NOT_FOUND = -30,
    GA_ERROR_INVALID_CONFIG = -31,
    GA_ERROR_VERSION_MISMATCH = -32,
    GA_ERROR_INVALID_SERVICE_SUBTYPE = -33,
    GA_ERROR_INVALID_PACKET = -34,
    GA_ERROR_INVALID_DNS_ERROR = -35,
    GA_ERROR_DNS_FORMERR = -36,
    GA_ERROR_DNS_SERVFAIL = -37,
    GA_ERROR_DNS_NXDOMAIN = -38,
    GA_ERROR_DNS_NOTIMP = -39,
    GA_ERROR_DNS_REFUSED = -40,
    GA_ERROR_DNS_YXDOMAIN = -41,
    GA_ERROR_DNS_YXRRSET = -42,
    GA_ERROR_DNS_NXRRSET = -43,
    GA_ERROR_DNS_NOTAUTH = -44,
    GA_ERROR_DNS_NOTZONE = -45,
    GA_ERROR_INVALID_RDATA = -46,
    GA_ERROR_INVALID_DNS_CLASS = -47,
    GA_ERROR_INVALID_DNS_TYPE = -48,
    GA_ERROR_NOT_SUPPORTED = -49,
    GA_ERROR_NOT_PERMITTED = -50,
    GA_ERROR_INVALID_ARGUMENT = -51,
    GA_ERROR_IS_EMPTY = -52,
    GA_ERROR_NO_CHANGE = -53
} GaErrorCode;

G_END_DECLS

#endif /* #ifndef __GA_ERROR_H__ */
