/* SPDX-License-Identifier: LGPL-2.1-or-later */

/*
 * Avahi drop-in compatibility wrapper for avahi-common/error.h
 *
 * This provides the Avahi error codes.
 */

#ifndef __AVAHI_COMMON_ERROR_H_COMPAT__
#define __AVAHI_COMMON_ERROR_H_COMPAT__

#include "../ga-error.h"

/*
 * Error codes are defined in ga-error.h as GA_ERROR_*.
 * They match the Avahi AVAHI_ERR_* values.
 */

/* Map GA_ERROR codes to AVAHI_ERR codes */
#define AVAHI_OK                    GA_ERROR_OK
#define AVAHI_ERR_FAILURE           GA_ERROR_FAILURE
#define AVAHI_ERR_BAD_STATE         GA_ERROR_BAD_STATE
#define AVAHI_ERR_INVALID_HOST_NAME GA_ERROR_INVALID_HOST_NAME
#define AVAHI_ERR_INVALID_DOMAIN_NAME GA_ERROR_INVALID_DOMAIN_NAME
#define AVAHI_ERR_NO_NETWORK        GA_ERROR_NO_NETWORK
#define AVAHI_ERR_INVALID_TTL       GA_ERROR_INVALID_TTL
#define AVAHI_ERR_IS_PATTERN        GA_ERROR_IS_PATTERN
#define AVAHI_ERR_COLLISION         GA_ERROR_COLLISION
#define AVAHI_ERR_INVALID_RECORD    GA_ERROR_INVALID_RECORD
#define AVAHI_ERR_INVALID_SERVICE_NAME GA_ERROR_INVALID_SERVICE_NAME
#define AVAHI_ERR_INVALID_SERVICE_TYPE GA_ERROR_INVALID_SERVICE_TYPE
#define AVAHI_ERR_INVALID_PORT      GA_ERROR_INVALID_PORT
#define AVAHI_ERR_INVALID_KEY       GA_ERROR_INVALID_KEY
#define AVAHI_ERR_INVALID_ADDRESS   GA_ERROR_INVALID_ADDRESS
#define AVAHI_ERR_TIMEOUT           GA_ERROR_TIMEOUT
#define AVAHI_ERR_TOO_MANY_CLIENTS  GA_ERROR_TOO_MANY_CLIENTS
#define AVAHI_ERR_TOO_MANY_OBJECTS  GA_ERROR_TOO_MANY_OBJECTS
#define AVAHI_ERR_TOO_MANY_ENTRIES  GA_ERROR_TOO_MANY_ENTRIES
#define AVAHI_ERR_OS                GA_ERROR_OS
#define AVAHI_ERR_ACCESS_DENIED     GA_ERROR_ACCESS_DENIED
#define AVAHI_ERR_INVALID_OPERATION GA_ERROR_INVALID_OPERATION
#define AVAHI_ERR_DBUS_ERROR        GA_ERROR_DBUS_ERROR
#define AVAHI_ERR_DISCONNECTED      GA_ERROR_DISCONNECTED
#define AVAHI_ERR_NO_MEMORY         GA_ERROR_NO_MEMORY
#define AVAHI_ERR_INVALID_OBJECT    GA_ERROR_INVALID_OBJECT
#define AVAHI_ERR_NO_DAEMON         GA_ERROR_NO_DAEMON
#define AVAHI_ERR_INVALID_INTERFACE GA_ERROR_INVALID_INTERFACE
#define AVAHI_ERR_INVALID_PROTOCOL  GA_ERROR_INVALID_PROTOCOL
#define AVAHI_ERR_INVALID_FLAGS     GA_ERROR_INVALID_FLAGS
#define AVAHI_ERR_NOT_FOUND         GA_ERROR_NOT_FOUND
#define AVAHI_ERR_INVALID_CONFIG    GA_ERROR_INVALID_CONFIG
#define AVAHI_ERR_VERSION_MISMATCH  GA_ERROR_VERSION_MISMATCH
#define AVAHI_ERR_INVALID_SERVICE_SUBTYPE GA_ERROR_INVALID_SERVICE_SUBTYPE
#define AVAHI_ERR_INVALID_PACKET    GA_ERROR_INVALID_PACKET
#define AVAHI_ERR_INVALID_DNS_ERROR GA_ERROR_INVALID_DNS_ERROR
#define AVAHI_ERR_DNS_FORMERR       GA_ERROR_DNS_FORMERR
#define AVAHI_ERR_DNS_SERVFAIL      GA_ERROR_DNS_SERVFAIL
#define AVAHI_ERR_DNS_NXDOMAIN      GA_ERROR_DNS_NXDOMAIN
#define AVAHI_ERR_DNS_NOTIMP        GA_ERROR_DNS_NOTIMP
#define AVAHI_ERR_DNS_REFUSED       GA_ERROR_DNS_REFUSED
#define AVAHI_ERR_DNS_YXDOMAIN      GA_ERROR_DNS_YXDOMAIN
#define AVAHI_ERR_DNS_YXRRSET       GA_ERROR_DNS_YXRRSET
#define AVAHI_ERR_DNS_NXRRSET       GA_ERROR_DNS_NXRRSET
#define AVAHI_ERR_DNS_NOTAUTH       GA_ERROR_DNS_NOTAUTH
#define AVAHI_ERR_DNS_NOTZONE       GA_ERROR_DNS_NOTZONE
#define AVAHI_ERR_INVALID_RDATA     GA_ERROR_INVALID_RDATA
#define AVAHI_ERR_INVALID_DNS_CLASS GA_ERROR_INVALID_DNS_CLASS
#define AVAHI_ERR_INVALID_DNS_TYPE  GA_ERROR_INVALID_DNS_TYPE
#define AVAHI_ERR_NOT_SUPPORTED     GA_ERROR_NOT_SUPPORTED
#define AVAHI_ERR_NOT_PERMITTED     GA_ERROR_NOT_PERMITTED
#define AVAHI_ERR_INVALID_ARGUMENT  GA_ERROR_INVALID_ARGUMENT
#define AVAHI_ERR_IS_EMPTY          GA_ERROR_IS_EMPTY
#define AVAHI_ERR_NO_CHANGE         GA_ERROR_NO_CHANGE

#endif /* __AVAHI_COMMON_ERROR_H_COMPAT__ */
